machine:
  node:
    version: 6.0.0
test:
  override:
    - npm test -- --coverage
  post:
    - npm install -g codeclimate-test-reporter
    - codeclimate-test-reporter < coverage/lcov.info
deployment:
  staging:
    branch: master
    heroku:
      appname: dendenmarvin.git #TODO: Change the name to that of permanent address 
      